/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        PowerSupply_PSW_3072Class.cpp
//
// description : C++ source for the PowerSupply_PSW_3072Class.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the PowerSupply_PSW_3072 once per process.
//
// project :     PowerSupply PSW_30-72 Gw Instek
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Elkin V. © JINR
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PowerSupply_PSW_3072Class.h>

/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class.cpp

//-------------------------------------------------------------------
/**
 *	Create PowerSupply_PSW_3072Class singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PowerSupply_PSW_3072_class(const char *name) {
		return PowerSupply_PSW_3072_ns::PowerSupply_PSW_3072Class::init(name);
	}
}

namespace PowerSupply_PSW_3072_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PowerSupply_PSW_3072Class *PowerSupply_PSW_3072Class::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::PowerSupply_PSW_3072Class(string &s)
 * description : 	constructor for the PowerSupply_PSW_3072Class
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PowerSupply_PSW_3072Class::PowerSupply_PSW_3072Class(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering PowerSupply_PSW_3072Class constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::constructor

	cout2 << "Leaving PowerSupply_PSW_3072Class constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::~PowerSupply_PSW_3072Class()
 * description : 	destructor for the PowerSupply_PSW_3072Class
 */
//--------------------------------------------------------
PowerSupply_PSW_3072Class::~PowerSupply_PSW_3072Class()
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PowerSupply_PSW_3072Class *PowerSupply_PSW_3072Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PowerSupply_PSW_3072Class(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PowerSupply_PSW_3072Class *PowerSupply_PSW_3072Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		MeasureUpdateClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *MeasureUpdateClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "MeasureUpdateClass::execute(): arrived" << endl;
	((static_cast<PowerSupply_PSW_3072 *>(device))->measure_update());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OnClass::execute(): arrived" << endl;
	((static_cast<PowerSupply_PSW_3072 *>(device))->on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OffClass::execute(): arrived" << endl;
	((static_cast<PowerSupply_PSW_3072 *>(device))->off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetVoltageLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetVoltageLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetVoltageLevelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PowerSupply_PSW_3072 *>(device))->set_voltage_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetCurrentLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetCurrentLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetCurrentLevelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PowerSupply_PSW_3072 *>(device))->set_current_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		UpdateCurrVoltLevelsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *UpdateCurrVoltLevelsClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "UpdateCurrVoltLevelsClass::execute(): arrived" << endl;
	((static_cast<PowerSupply_PSW_3072 *>(device))->update_curr_volt_levels());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetCurrVoltLevelsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetCurrVoltLevelsClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetCurrVoltLevelsClass::execute(): arrived" << endl;
	const Tango::DevVarDoubleArray *argin;
	extract(in_any, argin);
	((static_cast<PowerSupply_PSW_3072 *>(device))->set_curr_volt_levels(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum PowerSupply_PSW_3072Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerSupply_PSW_3072Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PowerSupply_PSW_3072Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::get_class_property()
 *	Description : Read database to initialize class property data members.
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::get_class_property()
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::get_class_property_before) ENABLED START -----*/
	
	//	Initialize class property data members
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::get_class_property_before
	//	Read class properties from database.
	cl_prop.push_back(Tango::DbDatum("TangoHost"));
	
	//	Call database and extract values
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;
	int	i = -1;

	//	Try to extract TangoHost value
	if (cl_prop[++i].is_empty()==false)	cl_prop[i]  >>  tangoHost;
	else
	{
		//	Check default value for TangoHost
		def_prop = get_default_class_property(cl_prop[i].name);
		if (def_prop.is_empty()==false)
		{
			def_prop    >>  tangoHost;
			cl_prop[i]  <<  tangoHost;
		}
	}
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::get_class_property_after) ENABLED START -----*/
	
	//	Check class property data members init
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::get_class_property_after

}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties
	prop_name = "TangoHost";
	prop_desc = "tango://IP:port/";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		cl_def_prop.push_back(data);
		add_wiz_class_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_class_prop(prop_name, prop_desc);

	//	Set Default device Properties
	prop_name = "Socket";
	prop_desc = "Socket Tango device name in format ``domain/family/member``";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("PowerSupply PSW_30-72 Gw Instek");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Tango Server for PowerSupply PSW_30-72 Instek.");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("PowerSupply_PSW_3072");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PowerSupply_PSW_3072(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PowerSupply_PSW_3072 *dev = static_cast<PowerSupply_PSW_3072 *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::attribute_factory_before
	//	Attribute : volt_meas
	volt_measAttrib	*volt_meas = new volt_measAttrib();
	Tango::UserDefaultAttrProp	volt_meas_prop;
	volt_meas_prop.set_description("the output voltage");
	volt_meas_prop.set_label("OutputVvoltage");
	volt_meas_prop.set_unit("V");
	//	standard_unit	not set for volt_meas
	//	display_unit	not set for volt_meas
	//	format	not set for volt_meas
	//	max_value	not set for volt_meas
	//	min_value	not set for volt_meas
	//	max_alarm	not set for volt_meas
	//	min_alarm	not set for volt_meas
	//	max_warning	not set for volt_meas
	//	min_warning	not set for volt_meas
	//	delta_t	not set for volt_meas
	//	delta_val	not set for volt_meas
	
	volt_meas->set_default_properties(volt_meas_prop);
	//	Not Polled
	volt_meas->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(volt_meas);

	//	Attribute : curr_meas
	curr_measAttrib	*curr_meas = new curr_measAttrib();
	Tango::UserDefaultAttrProp	curr_meas_prop;
	curr_meas_prop.set_description("the output current");
	curr_meas_prop.set_label("OutputCurrent");
	curr_meas_prop.set_unit("A");
	//	standard_unit	not set for curr_meas
	//	display_unit	not set for curr_meas
	//	format	not set for curr_meas
	//	max_value	not set for curr_meas
	//	min_value	not set for curr_meas
	//	max_alarm	not set for curr_meas
	//	min_alarm	not set for curr_meas
	//	max_warning	not set for curr_meas
	//	min_warning	not set for curr_meas
	//	delta_t	not set for curr_meas
	//	delta_val	not set for curr_meas
	
	curr_meas->set_default_properties(curr_meas_prop);
	//	Not Polled
	curr_meas->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(curr_meas);

	//	Attribute : volt_level
	volt_levelAttrib	*volt_level = new volt_levelAttrib();
	Tango::UserDefaultAttrProp	volt_level_prop;
	volt_level_prop.set_description("the voltage level in volts");
	volt_level_prop.set_label("VoltageLevel");
	volt_level_prop.set_unit("V");
	//	standard_unit	not set for volt_level
	//	display_unit	not set for volt_level
	//	format	not set for volt_level
	//	max_value	not set for volt_level
	//	min_value	not set for volt_level
	//	max_alarm	not set for volt_level
	//	min_alarm	not set for volt_level
	//	max_warning	not set for volt_level
	//	min_warning	not set for volt_level
	//	delta_t	not set for volt_level
	//	delta_val	not set for volt_level
	
	volt_level->set_default_properties(volt_level_prop);
	//	Not Polled
	volt_level->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(volt_level);

	//	Attribute : curr_level
	curr_levelAttrib	*curr_level = new curr_levelAttrib();
	Tango::UserDefaultAttrProp	curr_level_prop;
	curr_level_prop.set_description("The current level in amps");
	curr_level_prop.set_label("CurrentLevel");
	curr_level_prop.set_unit("A");
	//	standard_unit	not set for curr_level
	//	display_unit	not set for curr_level
	//	format	not set for curr_level
	//	max_value	not set for curr_level
	//	min_value	not set for curr_level
	//	max_alarm	not set for curr_level
	//	min_alarm	not set for curr_level
	//	max_warning	not set for curr_level
	//	min_warning	not set for curr_level
	//	delta_t	not set for curr_level
	//	delta_val	not set for curr_level
	
	curr_level->set_default_properties(curr_level_prop);
	//	Not Polled
	curr_level->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(curr_level);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::pipe_factory()
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::pipe_factory_before
	Tango::UserDefaultPipeProp udpp;
	PipeAttrsClass	*pPipeAttrs = new PipeAttrsClass("PipeAttrs",Tango::OPERATOR);
	udpp.set_description("name_of_device - The name of device\nvolt_meas - the output voltage\ncurr_meas - the output current\nvolt_level - the voltage level in volts\ncurr_level - the current level in amps\nState - State of device\nStatus - Status of device\ntimestamp - UNIX timestamp");
	udpp.set_label("Attributes for PSW 30-72");
	pPipeAttrs->set_default_properties(udpp);
	pipe_list.push_back(pPipeAttrs);

	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::command_factory()
{
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::command_factory_before


	//	Command MeasureUpdate
	MeasureUpdateClass	*pMeasureUpdateCmd =
		new MeasureUpdateClass("MeasureUpdate",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pMeasureUpdateCmd);

	//	Command On
	OnClass	*pOnCmd =
		new OnClass("On",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOnCmd);

	//	Command Off
	OffClass	*pOffCmd =
		new OffClass("Off",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOffCmd);

	//	Command SetVoltageLevel
	SetVoltageLevelClass	*pSetVoltageLevelCmd =
		new SetVoltageLevelClass("SetVoltageLevel",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"Voltage level in volts",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetVoltageLevelCmd);

	//	Command SetCurrentLevel
	SetCurrentLevelClass	*pSetCurrentLevelCmd =
		new SetCurrentLevelClass("SetCurrentLevel",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"The current level in amps.",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetCurrentLevelCmd);

	//	Command UpdateCurrVoltLevels
	UpdateCurrVoltLevelsClass	*pUpdateCurrVoltLevelsCmd =
		new UpdateCurrVoltLevelsClass("UpdateCurrVoltLevels",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pUpdateCurrVoltLevelsCmd);

	//	Command SetCurrVoltLevels
	SetCurrVoltLevelsClass	*pSetCurrVoltLevelsCmd =
		new SetCurrVoltLevelsClass("SetCurrVoltLevels",
			Tango::DEVVAR_DOUBLEARRAY, Tango::DEV_VOID,
			"arg[0] cuurent level\narg[1] volt level",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetCurrVoltLevelsCmd);

	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		PowerSupply_PSW_3072Class::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PowerSupply_PSW_3072Class::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PowerSupply_PSW_3072 *dev = static_cast<PowerSupply_PSW_3072 *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : PowerSupply_PSW_3072Class::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *PowerSupply_PSW_3072Class::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(PowerSupply_PSW_3072Class::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	PowerSupply_PSW_3072Class::Additional Methods
} //	namespace
